remote_theme: pages-themes/slate@v0.2.0
title: Telling Stories with Data ...
description: Little nuggets that tell some of my story as I've worked with data in different places and with different people. And what I've learnt along the way.  
logo: ""
relative_links:
  enabled: true
  collections: true
